/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ufl_hypogator_jackb_fuzzymatching_TwoGramIndexerJNI */

#ifndef _Included_org_ufl_hypogator_jackb_fuzzymatching_TwoGramIndexerJNI
#define _Included_org_ufl_hypogator_jackb_fuzzymatching_TwoGramIndexerJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ufl_hypogator_jackb_fuzzymatching_TwoGramIndexerJNI
 * Method:    openDirectory
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_ufl_hypogator_jackb_fuzzymatching_TwoGramIndexerJNI_openDirectory
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_ufl_hypogator_jackb_fuzzymatching_TwoGramIndexerJNI
 * Method:    openDimensioN
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_ufl_hypogator_jackb_fuzzymatching_TwoGramIndexerJNI_openDimensioN
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_ufl_hypogator_jackb_fuzzymatching_TwoGramIndexerJNI
 * Method:    fuzzyMatch
 * Signature: (Ljava/lang/String;DILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_ufl_hypogator_jackb_fuzzymatching_TwoGramIndexerJNI_fuzzyMatch
  (JNIEnv *, jobject, jstring, jdouble, jint, jstring);

/*
 * Class:     org_ufl_hypogator_jackb_fuzzymatching_TwoGramIndexerJNI
 * Method:    hasCurrent
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ufl_hypogator_jackb_fuzzymatching_TwoGramIndexerJNI_hasCurrent
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_ufl_hypogator_jackb_fuzzymatching_TwoGramIndexerJNI
 * Method:    getCurrentKey
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_org_ufl_hypogator_jackb_fuzzymatching_TwoGramIndexerJNI_getCurrentKey
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_ufl_hypogator_jackb_fuzzymatching_TwoGramIndexerJNI
 * Method:    getCurrentValue
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_ufl_hypogator_jackb_fuzzymatching_TwoGramIndexerJNI_getCurrentValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_ufl_hypogator_jackb_fuzzymatching_TwoGramIndexerJNI
 * Method:    next
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ufl_hypogator_jackb_fuzzymatching_TwoGramIndexerJNI_next
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_ufl_hypogator_jackb_fuzzymatching_TwoGramIndexerJNI
 * Method:    containsExactTerm
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_ufl_hypogator_jackb_fuzzymatching_TwoGramIndexerJNI_containsExactTerm
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_ufl_hypogator_jackb_fuzzymatching_TwoGramIndexerJNI
 * Method:    closeDimension
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_ufl_hypogator_jackb_fuzzymatching_TwoGramIndexerJNI_closeDimension
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_ufl_hypogator_jackb_fuzzymatching_TwoGramIndexerJNI
 * Method:    closeDirectory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ufl_hypogator_jackb_fuzzymatching_TwoGramIndexerJNI_closeDirectory
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
