/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ufl_hypogator_jackb_traversers_conceptnet_JNIEntryPoint */

#ifndef _Included_org_ufl_hypogator_jackb_traversers_conceptnet_JNIEntryPoint
#define _Included_org_ufl_hypogator_jackb_traversers_conceptnet_JNIEntryPoint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ufl_hypogator_jackb_traversers_conceptnet_JNIEntryPoint
 * Method:    pg
 * Signature: (JZJ)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_ufl_hypogator_jackb_traversers_conceptnet_JNIEntryPoint_pgObjectOut
  (JNIEnv *, jobject, jlong, jboolean, jlong);

/*
 * Class:     org_ufl_hypogator_jackb_traversers_conceptnet_JNIEntryPoint
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ufl_hypogator_jackb_traversers_conceptnet_JNIEntryPoint_dispose
  (JNIEnv *, jobject);

/*
 * Class:     org_ufl_hypogator_jackb_traversers_conceptnet_JNIEntryPoint
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ufl_hypogator_jackb_traversers_conceptnet_JNIEntryPoint_init
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
